import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {promises as fs} from 'node:fs';
import path from 'node:path';
import {randomUUID} from 'node:crypto';

const physical=process.argv.includes('--physical'),base='http://127.0.0.1:8797';
const dir=path.resolve('.test-recordings','rig-'+randomUUID());await fs.mkdir(dir,{recursive:true});
const server=spawn(process.execPath,['server.mjs'],{env:{...process.env,PORT:'8797',RECORDINGS_DIR:dir},windowsHide:true,stdio:['ignore','pipe','pipe']});
let browser;
try{
 await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject);server.once('exit',code=>reject(new Error(`Test server exited ${code}`)));});
 browser=await chromium.launch({executablePath:'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',headless:true,args:['--use-fake-ui-for-media-stream']});
 const context=await browser.newContext({viewport:{width:1440,height:1080},permissions:['camera']});
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(`${base}/rig.html${physical?'':'?demo=1'}`);
 await page.waitForFunction(()=>!document.getElementById('connect-rig').disabled);
 await page.getByRole('button',{name:'Find cameras',exact:true}).click();
 await page.waitForFunction(()=>!document.getElementById('scan-cameras').disabled && !document.getElementById('device-status').textContent.includes('Scanning'),null,{timeout:20000});
 if(!physical){
  assert.equal(await page.locator('#camera-grid .camera-tile').count(),2);
  assert.equal((await(await fetch(base+'/api/rigs')).json()).length,0);
  for(let i=0;i<4;i++)await page.getByRole('button',{name:'+ Add camera',exact:true}).click();
  await page.getByRole('button',{name:'Remove Camera 3',exact:true}).click();
  await page.getByRole('button',{name:'+ Add camera',exact:true}).click();
  assert.equal(await page.locator('#camera-grid .camera-tile').count(),6);
  await page.reload();await page.waitForFunction(()=>document.querySelectorAll('#camera-grid .camera-tile').length===6);
  const ids=await page.locator('#camera-grid .camera-tile').evaluateAll(els=>els.map(el=>Number(el.dataset.slot)));assert.deepEqual(ids,[0,1,3,4,5,6]);
  assert.deepEqual(await page.locator('[id^="width-"]').evaluateAll(els=>els.map(el=>el.value)),Array(6).fill('1280'));
  assert.deepEqual(await page.locator('[id^="height-"]').evaluateAll(els=>els.map(el=>el.value)),Array(6).fill('720'));
  assert.deepEqual(await page.locator('[id^="framerate-"]').evaluateAll(els=>els.map(el=>el.value)),Array(6).fill('60'));
  await page.locator('#earlier-6').click();assert.deepEqual(await page.locator('#camera-grid .camera-tile').evaluateAll(els=>els.map(el=>Number(el.dataset.slot))),[0,1,3,4,6,5]);
  assert.deepEqual(await page.locator('.camera-number').allTextContents(),['Camera 1','Camera 2','Camera 3','Camera 4','Camera 5','Camera 6']);
  await page.locator('#later-6').click();
  await page.locator('#camera-6').selectOption('');
  await page.reload();await page.waitForFunction(()=>!document.getElementById('scan-cameras').disabled);
  assert.equal(await page.locator('#camera-6').inputValue(),'');
  await page.locator('#camera-6').selectOption('simulated-6');
 }
 const count=await page.locator('#camera-grid select[id^="camera-"]').evaluateAll(els=>els.filter(el=>el.value).length);
 await page.locator('[data-lab-tab="experiments"]').click();
 await page.locator('#experiment-title').fill('Automated multi-camera experiment');
 await page.locator('#experiment-group').fill('Software verification');
 await page.locator('#experiment-hypothesis').fill('Recording many streams preserves every angle and the experiment context.');
 await page.locator('#experiment-criteria').fill('Replay all streams, preserve bytes and notes, and verify separate session folders.');
 await page.getByRole('button',{name:'Save experiment',exact:true}).click();
 await page.getByRole('button',{name:'Use for capture ↗',exact:true}).click();
 assert.equal(await page.locator('#record-rig').isDisabled(),true);
 await page.locator('#session-change').fill('Six synthetic cameras for concurrency testing.');
 await page.locator('#session-procedure').fill('Capture the moving test patterns, then seek and play each recording.');
 assert.ok(count>=2,`Expected two cameras; detected ${count}`);
 await page.getByRole('button',{name:'Connect selected cameras',exact:true}).click();
 await page.waitForFunction(n=>document.getElementById('ready-count').textContent.startsWith(`${n} /`),count,{timeout:60000});
 if(!physical)assert.equal(await page.locator('.camera-footer strong').filter({hasText:'Requested 1280 × 720 @ 60 · received 1280 × 720 @ 60 ✓'}).count(),count);
 // Preview must not create a recording.
 assert.equal((await(await fetch(base+'/api/rigs')).json()).length,0);
 const settings=await page.locator('#camera-grid video').evaluateAll(els=>els.filter(v=>v.srcObject).map(v=>{const s=v.srcObject.getVideoTracks()[0].getSettings();return {width:s.width,height:s.height,frameRate:s.frameRate,deviceId:s.deviceId};}));
 if(physical)assert.equal(new Set(settings.map(s=>s.deviceId)).size,count);
 await page.getByRole('button',{name:'Record connected cameras',exact:true}).click();
 await page.waitForFunction(()=>document.getElementById('record-rig').textContent==='Stop & save all cameras');
 assert.equal(await page.locator('#add-camera').isDisabled(),true);
 assert.equal(await page.locator('.remove-camera').first().isDisabled(),true);
 await page.getByRole('button',{name:'Mark a visible sync cue',exact:true}).click();
 await page.waitForTimeout(12000);
 await page.getByRole('button',{name:'Stop & save all cameras',exact:true}).click();
 await page.waitForFunction(()=>document.getElementById('rig-save-status').textContent.startsWith('Experiment saved:'),null,{timeout:60000});
 const saved=(await(await fetch(base+'/api/rigs')).json())[0];assert.equal(saved.cameras.length,count);assert.equal(saved.status,'saved');
 assert.ok(saved.cameras.every(c=>c.recording.bytes>1000&&c.timingSamples>0));
 await page.locator('[data-lab-tab="library"]').click();
 await page.getByRole('button',{name:'Review angles',exact:true}).first().click();
 await page.getByRole('button',{name:'Play all angles',exact:true}).click();
 await page.waitForFunction(()=>Array.from(document.querySelectorAll('#review-grid video')).every(v=>v.currentTime>.3));
 await page.getByRole('button',{name:'Pause all angles',exact:true}).click();
 await page.locator('#review-time').evaluate(el=>{el.value='4';el.dispatchEvent(new Event('input',{bubbles:true}));});
 await page.waitForFunction(()=>Array.from(document.querySelectorAll('#review-grid video')).every(v=>Math.abs(v.currentTime-4)<.5));
 await page.getByRole('button',{name:'Assess take',exact:true}).click();
 await page.waitForSelector('.quality-gate',{timeout:60000});
 assert.match(await page.locator('#quality-report').innerText(),/realism score: not established/);
 assert.equal(await page.locator('.quality-gate').count(),8);
 const quality=await(await fetch(base+`/api/rigs/${saved.id}/quality`)).json();assert.equal(quality.realismScore,null);
 assert.equal(quality.gates.find(g=>g.id==='geometry').status,'fail');
 if(!physical){
  await page.screenshot({path:'artifacts/dynamic-rig-assessment.png',fullPage:true});
  await page.locator('#takes-list .take-row').first().getByRole('button',{name:'Reconstruct combined 3D',exact:true}).click();
  assert.equal(await page.locator('[data-camera-slot]:checked').count(),6);
  assert.match(await page.locator('#reconstruction-budget').textContent(),/300 optimization steps/);
  await page.locator('[data-camera-slot]').nth(4).uncheck();await page.locator('[data-camera-slot]').nth(5).uncheck();
  assert.equal(await page.locator('[data-camera-slot]:checked').count(),4);assert.match(await page.locator('#reconstruction-budget').textContent(),/200 optimization steps/);
  await page.locator('[data-lab-tab="capture"]').click();
  // Removing a connected slot must release its stream and preserve saved take membership.
  await page.evaluate(()=>{window.removedTrack=document.querySelector('#preview-3').srcObject.getVideoTracks()[0];});
  await page.getByRole('button',{name:'Remove Camera 3',exact:true}).click();
  assert.equal(await page.evaluate(()=>window.removedTrack.readyState),'ended');
  assert.equal((await(await fetch(base+`/api/rigs/${saved.id}`)).json()).cameras.length,count);
  await page.getByRole('button',{name:'Disconnect all',exact:true}).click();
  while(await page.locator('.remove-camera').count()>2)await page.locator('.remove-camera').last().click();
  await page.getByRole('button',{name:'Connect selected cameras',exact:true}).click();
  await page.waitForFunction(()=>document.getElementById('ready-count').textContent.startsWith('2 / 2 camera slots connected'));
  assert.equal(await page.locator('#record-rig').isDisabled(),true);
  await page.locator('#session-change').fill('Reduced the rig to two synthetic camera streams.');
  await page.locator('#session-procedure').fill('Capture two seconds and compare archive independence.');
  await page.getByRole('button',{name:'Record connected cameras',exact:true}).click();
  await page.waitForFunction(()=>document.getElementById('record-rig').textContent==='Stop & save all cameras');
  await page.waitForTimeout(2200);
  await page.getByRole('button',{name:'Stop & save all cameras',exact:true}).click();
  await page.waitForFunction(()=>document.getElementById('rig-save-status').textContent.startsWith('Experiment saved:'),null,{timeout:30000});
  assert.equal((await(await fetch(base+'/api/rigs')).json())[0].cameras.length,2);
  const experiments=await(await fetch(base+'/api/experiments')).json();assert.equal(experiments.length,2);assert.equal(new Set(experiments.map(e=>e.path)).size,2);
  assert.deepEqual(experiments.map(e=>e.originals.length).sort(),[2,6]);
  for(const experiment of experiments)for(const camera of experiment.originals)assert.deepEqual(await fs.readFile(path.join(experiment.path,camera.file)),await fs.readFile(path.join(dir,camera.sessionId,'recording.webm')));
  await page.locator('[data-lab-tab="experiments"]').click();
  await page.locator('#lab-experiment-list button').first().click();
  assert.equal(await page.locator('.session-history-row').count(),2);
  await page.locator('#note-text').fill('Both recordings saved separately. This is a software test, not a physical reconstruction benchmark.');
  await page.getByRole('button',{name:'Add note',exact:true}).click();
  await page.waitForSelector('.notebook-note');
  const labs=await(await fetch(base+'/api/lab/experiments')).json();assert.equal(labs.length,1);assert.equal(labs[0].sessionCount,2);assert.equal(labs[0].notes.length,1);
  await page.locator('[data-lab-tab="capture"]').click();
  await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 }
 await page.getByRole('button',{name:'Disconnect all',exact:true}).click();
 if(!physical){await page.reload();await page.waitForFunction(()=>document.querySelectorAll('#takes-list [data-take-id]').length===2);}
 assert.deepEqual(errors,[]);
 const result={physical,settings,rigId:saved.id,cameraCount:count,quality,pageErrors:errors,recordingsDir:dir};
 await fs.writeFile(`artifacts/${physical?'physical':'simulated'}-rig-audit.json`,JSON.stringify(result,null,2));
 console.log(JSON.stringify({pass:true,physical,cameras:count,verifiedGates:quality.verifiedGates,verdict:quality.verdict,recordingsDir:dir}));
}finally{await browser?.close();server.kill();}
