import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawn,execFileSync } from 'node:child_process';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import http from 'node:http';

test('recording API preserves ordered bytes, rejects hostile requests, and produces seekable playback',async()=>{
 const dir=path.resolve('.test-recordings','api-'+randomUUID());await fs.mkdir(dir,{recursive:true});
 const child=spawn(process.execPath,['server.mjs'],{env:{...process.env,PORT:'8796',RECORDINGS_DIR:dir},windowsHide:true,stdio:['ignore','pipe','pipe']});
 try{
  await new Promise((resolve,reject)=>{child.stdout.once('data',resolve);child.once('error',reject);child.once('exit',code=>reject(new Error('Server exited '+code)));});
  const base='http://127.0.0.1:8796',config=await(await fetch(base+'/api/config')).json();
  const request=(endpoint,body,headers={})=>fetch(base+endpoint,{method:'POST',headers:{'X-Spatial-Token':config.token,...headers},body:typeof body==='object'&&!Buffer.isBuffer(body)?JSON.stringify(body):body});
  assert.equal((await fetch(base+'/api/sessions',{method:'POST',body:'{}'})).status,403);
  assert.equal((await request('/api/sessions',{}, {Origin:'https://untrusted.example'})).status,403);
  assert.equal((await fetch(base+'/api/reconstructions',{method:'POST',body:'{}'})).status,403);
  assert.equal((await request('/api/reconstructions',{})).status,400);
  assert.equal((await request('/api/reconstructions',{rigId:randomUUID(),profile:'quick',mode:'moment',method:'multiview',surfaceGuidance:'false',time:10,offsetMs:0,hfov:70,slots:[0,1]})).status,400);
  assert.equal((await request('/api/reconstructions',{rigId:randomUUID(),profile:'quick',mode:'moment',method:'multiview',time:10,offsetMs:0,hfov:70,slots:[0,0]})).status,400);
  assert.equal((await request('/api/reconstructions',{rigId:'../../escape',profile:'quick',mode:'moment'})).status,400);
  assert.equal((await fetch(base+'/api/reconstructions/not-a-job/frame-00000.splat')).status,404);
  const hostileHost=await new Promise((resolve,reject)=>{http.get(base+'/api/config',{headers:{Host:'attacker.invalid'}},r=>{r.resume();resolve(r.statusCode);}).on('error',reject);});assert.equal(hostileHost,403);
  const created=await request('/api/sessions',{name:'API verification'});assert.equal(created.status,201);const session=await created.json();
  const fixture=path.join(dir,'fixture.webm');execFileSync('ffmpeg',['-v','error','-y','-f','lavfi','-i','testsrc2=size=320x180:rate=20','-t','2','-c:v','libvpx','-an',fixture],{windowsHide:true});
  const data=await fs.readFile(fixture),split=Math.floor(data.length/2),a=data.subarray(0,split),b=data.subarray(split);
  const route=`/api/sessions/${session.id}`;
  assert.equal((await request(route+'/chunk?seq=1&time=1',b)).status,409);
  assert.equal((await request(route+'/chunk?seq=0&time=1',a)).status,200);
  const duplicate=await(await request(route+'/chunk?seq=0&time=1',a)).json();assert.equal(duplicate.duplicate,true);
  assert.equal((await request(route+'/chunk?seq=1&time=2',b)).status,200);
  assert.deepEqual(await fs.readFile(path.join(dir,session.id,'capture.webm')),data);
  const depth=Buffer.alloc(8+4*4*2);depth.writeUInt32LE(4,0);depth.writeUInt32LE(4,4);
  assert.equal((await request(route+'/depth?ms=0',depth)).status,200);
  assert.equal((await request(route+'/depth?ms=0&quality=hq',depth)).status,200);
  assert.deepEqual(await(await fetch(base+route+'/depth-index?quality=hq')).json(),[0]);
  assert.equal((await fetch(base+`/recordings/${session.id}/depth-hq/0.bin`)).status,200);
  assert.equal((await request(route+'/depth?ms=-1',depth)).status,400);
  const stopped=await request(route+'/stop',{});assert.equal(stopped.status,200);const saved=await stopped.json();assert.equal(saved.status,'saved');
  assert.equal(saved.depthFrames,1);assert.equal(saved.hqDepthFrames,1);
  const frameTimes=await(await fetch(base+route+'/frame-times')).json();assert.equal(frameTimes.length,40);assert.equal(frameTimes[0],0);
  const range=await fetch(base+saved.url,{headers:{Range:'bytes=0-99'}});assert.equal(range.status,206);assert.equal((await range.arrayBuffer()).byteLength,100);
  assert.equal((await fetch(base+saved.url,{headers:{Range:'bytes=999999999-'}})).status,416);
  const result=JSON.parse(execFileSync('ffprobe',['-v','error','-show_entries','format=duration','-of','json',path.join(dir,session.id,'recording.webm')],{windowsHide:true,encoding:'utf8'}));assert.ok(Number(result.format.duration)>=1.9);
  assert.equal((await request(route+'/chunk?seq=2&time=3',b)).status,409);
  const cameras=Array.from({length:6},(_,i)=>({slot:i*7,label:`Camera ${i+1}`,deviceId:`test-device-${i}`,deviceLabel:`Synthetic camera ${i+1}`,width:320,height:180,frameRate:20}));
  const plan={title:'Six-view software test',hypothesis:'Six independent streams remain recoverable and keep provenance.',successCriteria:'Every source byte and session context survives reload.',group:'Software verification'};
  const experiment=await(await request('/api/lab/experiments',plan)).json();assert.ok(experiment.id);
  const context={experimentId:experiment.id,whatChanged:'Six simulated input streams.',procedure:'Record two seconds of the same generated test signal.'};
  assert.equal((await request('/api/rigs',{cameras,clockOriginUnixMs:Date.now()})).status,400);
  assert.equal((await request('/api/rigs',{cameras,clockOriginUnixMs:Date.now(),context:{...context,whatChanged:''}})).status,400);
  assert.equal((await request('/api/rigs',{cameras:[cameras[0],cameras[0]],clockOriginUnixMs:Date.now()})).status,400);
  assert.equal((await request('/api/rigs',{cameras:[null],clockOriginUnixMs:Date.now()})).status,400);
  assert.equal((await request('/api/rigs',{cameras:[{...cameras[0],slot:-1}],clockOriginUnixMs:Date.now()})).status,400);
  assert.equal((await request('/api/rigs',{cameras:[cameras[0],{...cameras[1],deviceId:cameras[0].deviceId}],clockOriginUnixMs:Date.now()})).status,400);
  const groupResponse=await request('/api/rigs',{name:'Six-stream API test',context,simulated:true,cameras,clockOriginUnixMs:Date.now()});assert.equal(groupResponse.status,201);const group=await groupResponse.json();
  assert.equal(group.cameras.length,6);assert.equal(new Set(group.cameras.map(c=>c.sessionId)).size,6);assert.equal(group.timebase.exposureSynchronized,false);
  assert.equal((await fetch(base+`/api/rigs/${group.id}/quality`)).status,409);
  assert.equal((await request(`/api/rigs/${group.id}/finish`,{cameras:[],markers:[]})).status,409);
  await Promise.all(group.cameras.map(async(c)=>{
    const r=`/api/sessions/${c.sessionId}`;
    assert.equal((await request(r+'/chunk?seq=0&time=1',a)).status,200);
    assert.equal((await request(r+'/chunk?seq=1&time=2',b)).status,200);
    const timing=`/api/rigs/${group.id}/timing`;
    assert.equal((await request(timing,{slot:c.slot,seq:1,samples:[]})).status,409);
    assert.equal((await request(timing,{slot:c.slot,seq:0,samples:[[0,0,0],[50,50,1]]})).status,200);
    assert.equal((await(await request(timing,{slot:c.slot,seq:0,samples:[[0,0,0]]})).json()).duplicate,true);
    assert.equal((await request(r+'/stop',{})).status,200);
    assert.deepEqual(await fs.readFile(path.join(dir,c.sessionId,'capture.webm')),data);
  }));
  const summary={cameras:cameras.map(c=>({slot:c.slot,startRequestedMs:c.slot,stopRequestedMs:2000+c.slot,observedFrames:40})),markers:[{ms:100,label:'Visual cue'}]};
  const groupSaved=await request(`/api/rigs/${group.id}/finish`,summary);assert.equal(groupSaved.status,200);assert.equal((await groupSaved.json()).status,'saved');
  const manifest=await(await fetch(base+`/api/rigs/${group.id}/manifest`)).json();assert.equal(manifest.cameras.length,6);assert.ok(manifest.cameras.every(c=>c.timingSamples===2&&c.recording.status==='saved'));assert.equal(manifest.calibration,null);assert.equal(manifest.reconstruction,null);
  const assessment=await(await fetch(base+`/api/rigs/${group.id}/quality`)).json();
  assert.equal(assessment.realismScore,null);assert.equal(assessment.verdict,'SOFTWARE TEST ONLY');assert.equal(assessment.verifiedGates,1);
  assert.ok(assessment.cameras.every(c=>c.encoded.frames===40&&Math.abs(c.encoded.effectiveFps-20)<.01));
  assert.equal(assessment.gates.find(g=>g.id==='cadence').status,'fail');
  assert.equal(assessment.gates.find(g=>g.id==='geometry').status,'fail');
  assert.equal((await request(`/api/rigs/${group.id}/timing`,{slot:0,seq:1,samples:[]})).status,409);
  assert.equal((await request(`/api/rigs/${group.id}/finish`,summary)).status,200);
  const noted=await(await request(`/api/lab/experiments/${experiment.id}/notes`,{revision:1,kind:'observation',text:'Source bytes survived the complete capture workflow.'})).json();assert.equal(noted.revision,2);
  assert.equal((await request(`/api/lab/experiments/${experiment.id}`,{...plan,revision:1})).status,409);
  const revised=await(await request(`/api/lab/experiments/${experiment.id}`,{...plan,title:'Updated test hypothesis title',revision:2})).json();assert.equal(revised.revision,3);
  const evidence=await(await fetch(base+`/api/lab/experiments/${experiment.id}/report.json`)).json();assert.equal(evidence.sessions.length,1);assert.equal(evidence.sessions[0].context.title,plan.title);assert.equal(evidence.experiment.notes.length,1);assert.equal(evidence.experiment.history.length,1);
  assert.match(await(await fetch(base+`/api/lab/experiments/${experiment.id}/report.md`)).text(),/Six simulated input streams/);
  console.log('Verified: six concurrent streams with sparse slot IDs, original bytes, timing retries, playback and strict assessment.');
  console.log('Verified:',data.length,'source bytes, retry deduplication, seekable duration',result.format.duration);
 }finally{child.kill();}
});
