import './remote-phone.css';
import {CombinedViewer} from './combined-viewer.js';
const $=id=>document.getElementById(id),pairKey='spatial-desktop-pairing-v1';
let pairing=null,state=null,viewer=null,manifest=null,jobId=null,frameIndex=0,loading=false,loadVersion=0,playing=false,playOrigin=0,move=null,lastTick=0,refreshing=false,polling=false,requestBusy=false,lastLibrary=0;
const cache=new Map();
function error(e){$('error').textContent=e.message||String(e);$('error').hidden=false;}
function clearError(){$('error').hidden=true;}
function validPair(value){const url=new URL(value.url);if(url.username||url.password||url.search||url.hash||url.pathname!=='/')throw new Error('Use only the desktop connection origin.');const tunnel=url.protocol==='https:'&&['.trycloudflare.com','.ngrok-free.dev','.ngrok.app'].some(suffix=>url.hostname.endsWith(suffix));if(!tunnel&&!(url.protocol==='http:'&&['127.0.0.1','localhost'].includes(url.hostname)))throw new Error('Use your HTTPS desktop tunnel URL.');if(!/^[a-f0-9]{64}$/.test(value.key))throw new Error('Enter the complete private access key.');return {url:url.origin,key:value.key};}
async function request(path,options={}){if(!pairing)throw new Error('Connect the desktop first.');const r=await fetch(pairing.url+path,{...options,headers:{Authorization:'Bearer '+pairing.key,'ngrok-skip-browser-warning':'1',...options.headers},cache:'no-store',signal:AbortSignal.timeout(120000)});if(!r.ok){let msg;try{msg=(await r.json()).error;}catch{}throw new Error(msg||`Desktop request failed (${r.status})`);}return r;}
const api=async path=>(await request(path)).json(),post=async(path,value)=>(await request(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)})).json();
function node(tag,text,cls){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el;}
async function connect(value){pairing=validPair(value);await api('/api/remote/state');localStorage.setItem(pairKey,JSON.stringify(pairing));sessionStorage.removeItem(pairKey);$('pairing').hidden=true;$('workspace').hidden=false;clearError();await experiments();await library();await poll();}
$('pair-form').onsubmit=e=>{e.preventDefault();connect({url:$('bridge-url').value,key:$('bridge-key').value.trim()}).catch(error);};
$('disconnect').onclick=()=>{pairing=null;localStorage.removeItem(pairKey);sessionStorage.removeItem(pairKey);playing=false;move=null;$('workspace').hidden=true;$('pairing').hidden=false;$('connection').textContent='Not connected';};
async function experiments(){const entries=await api('/api/lab/experiments'),prior=$('experiment').value;$('experiment').replaceChildren(new Option('Choose an experiment',''),...entries.filter(e=>e.status!=='reviewed').map(e=>new Option(e.title,e.id)));if(entries.some(e=>e.id===prior))$('experiment').value=prior;}
$('show-new').onclick=()=>{$('new-experiment').hidden=!$('new-experiment').hidden;};
$('new-experiment').onsubmit=async e=>{e.preventDefault();try{const saved=await post('/api/lab/experiments',{title:$('new-title').value,hypothesis:$('new-question').value,successCriteria:$('new-criteria').value,status:'active'});await experiments();$('experiment').value=saved.id;$('new-experiment').hidden=true;clearError();}catch(e){error(e);}};
function controls(){const busy=requestBusy||['queued','running'].includes(state?.command?.status);$('start').disabled=!state?.online||state.recording||state.saving||state.processing||busy||!state.cameras.some(c=>c.connected);$('stop').disabled=!state?.online||!state.recording||state.saving||busy;}
async function command(action){requestBusy=true;controls();try{clearError();if(action==='start'&&(!$('experiment').value||$('context').value.trim().length<5))throw new Error('Choose an experiment and add session context.');const result=await post('/api/remote/commands',{id:crypto.randomUUID(),action,seconds:Number($('seconds').value),profile:$('quality').value,maxGaussians:Number($('splat-limit').value),requireQuality:$('require-quality').checked,context:{experimentId:$('experiment').value,label:$('session-label').value,whatChanged:$('context').value,procedure:$('context').value}});state.command=result;$('capture-state').textContent='Command sent to desktop…';}catch(e){error(e);}finally{requestBusy=false;controls();}}
$('start').onclick=()=>command('start');$('stop').onclick=()=>command('stop');
function renderCameras(){const host=$('cameras'),signature=state.cameras.map(c=>c.slot).join(',');if(host.dataset.slots!==signature){host.dataset.slots=signature;host.replaceChildren(...state.cameras.map(c=>{const card=node('article',undefined,'camera');card.dataset.slot=c.slot;const img=node('img');img.alt=c.label+' latest desktop preview';card.append(node('h3',c.label),img,node('p'));return card;}));}for(const c of state.cameras){const card=[...host.children].find(el=>el.dataset.slot===String(c.slot));if(!card)continue;if(c.image)card.querySelector('img').src=c.image;card.querySelector('img').hidden=!c.image;card.querySelector('p').textContent=c.connected?`${c.width} × ${c.height} · ${(c.fps||0).toFixed(1)} / ${c.requestedFps||'?'} FPS · ${state.online?'latest snapshot':'stale snapshot'}`:'Not connected';}$('camera-count').textContent=`${state.cameras.filter(c=>c.connected).length} connected`;}
async function poll(){if(!pairing||polling)return;polling=true;try{state=await api('/api/remote/state');$('connection').textContent=state.online?'● Desktop connected':'Desktop offline';controls();renderCameras();$('capture-state').textContent=!state.online?'Desktop is offline. Keep the PC awake and the camera page open.':state.saving?'Saving originals and starting reconstruction…':state.recording?'Recording on the PC. You may close this phone page; the timed recording will finish.':state.processing?'Processing the saved replay on your PC…':'Ready for a new session.';if(state.command?.status==='failed')$('capture-state').textContent='Command failed: '+state.command.error;if(Date.now()-lastLibrary>6500)await library();}catch(e){$('connection').textContent='Connection interrupted';state={...state,online:false};controls();$('capture-state').textContent=e.message;}finally{polling=false;}}
setInterval(poll,2000);
async function library(){if(refreshing)return;refreshing=true;try{const [takes,jobs]=await Promise.all([api('/api/rigs'),api('/api/reconstructions')]);lastLibrary=Date.now();const host=$('sessions');host.replaceChildren();for(const take of takes){const row=node('article',undefined,'session-row');row.append(node('strong',take.name),node('small',`${new Date(take.created).toLocaleString()} · ${take.cameras.length} cameras · ${take.status}`));const builds=jobs.filter(j=>j.rigId===take.id);for(const job of builds.slice(0,3)){row.append(node('p',`${job.profile} · ${job.state} · ${Math.round((job.progress||0)*100)}% · ${job.error||job.stage||''}`,'job-state'));if(job.state==='complete'){const open=node('button','Open 3D replay');open.onclick=()=>openReplay(job.id,take.name).catch(error);row.append(open);}}if(take.status==='saved'&&take.cameras.length>=2&&!builds.some(j=>j.state==='running')){const build=node('button','Process replay','secondary');build.disabled=!!state?.processing;build.onclick=async()=>{build.disabled=true;try{await post('/api/reconstructions',{rigId:take.id,slots:take.cameras.map(c=>c.slot),offsetsMs:take.cameras.map(()=>0),profile:$('quality').value,mode:'sequence',method:'multiview',surfaceGuidance:true,optimizations:true,maxGaussians:Number($('splat-limit').value),time:0,offsetMs:0,hfov:70});await library();}catch(e){error(e);}finally{build.disabled=false;}};row.append(build);}host.append(row);}if(!takes.length)host.append(node('p','Record your first session to build a replay.','muted'));}finally{refreshing=false;}}
$('refresh').onclick=()=>Promise.all([experiments(),library(),poll()]).catch(error);
async function openReplay(id,title){playing=false;const m=await api(`/api/reconstructions/${id}/manifest.json`);if(!m.frames?.length)throw new Error('The reconstruction has no frames.');jobId=id;manifest=m;cache.clear();loadVersion++;$('replay').hidden=false;$('replay-title').textContent=title;viewer||=new CombinedViewer($('scene'));viewer.setCalibration(m);viewer.setMode($('navigation').value);$('timeline').min=m.frames[0].time;$('timeline').max=m.frames.at(-1).time;frameIndex=0;await loadFrame(0);$('replay').scrollIntoView({behavior:'smooth'});}
async function loadFrame(index){if(!manifest)return;const version=++loadVersion,id=jobId,m=manifest,f=m.frames[index];frameIndex=index;loading=true;$('timeline').value=f.time;$('replay-status').textContent=`Loading ${f.time.toFixed(2)} s…`;try{if(!cache.has(index)){if(!/^frame-\d{5}\.splat$/.test(f.file))throw new Error('Invalid replay frame');cache.set(index,request(`/api/reconstructions/${id}/${f.file}`).then(r=>r.arrayBuffer()).catch(e=>{cache.delete(index);throw e;}));}const bytes=await cache.get(index);while(cache.size>3)cache.delete(cache.keys().next().value);if(version!==loadVersion||m!==manifest)return;viewer.load(bytes,{fraction:Number($('density').value)/100});$('replay-status').textContent=`${f.time.toFixed(2)} s · ${index+1}/${m.frames.length} samples · ${viewer.visibleCount.toLocaleString()} / ${viewer.totalCount.toLocaleString()} splats`;if(playing)playOrigin=performance.now()-f.time*1000;}finally{if(version===loadVersion)loading=false;}}
function nearest(time){return manifest.frames.reduce((best,f,i)=>Math.abs(f.time-time)<Math.abs(manifest.frames[best].time-time)?i:best,0);}
$('timeline').oninput=()=>{if(manifest){playing=false;$('play').textContent='Play';loadFrame(nearest(Number($('timeline').value))).catch(error);}};
$('density').oninput=()=>{if(manifest)loadFrame(frameIndex).catch(error);};
$('play').onclick=()=>{if(!manifest)return;playing=!playing;if(playing&&frameIndex===manifest.frames.length-1){frameIndex=0;loadFrame(0).catch(error);}playOrigin=performance.now()-manifest.frames[frameIndex].time*1000;$('play').textContent=playing?'Pause':'Play';};
$('home').onclick=()=>viewer?.snap(0);$('navigation').onchange=()=>viewer?.setMode($('navigation').value);
for(const b of document.querySelectorAll('[data-move]')){b.onpointerdown=e=>{e.preventDefault();move=b.dataset.move;b.setPointerCapture(e.pointerId);};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>{move=null;};}
window.addEventListener('blur',()=>{move=null;});document.addEventListener('visibilitychange',()=>{move=null;if(document.hidden){playing=false;$('play').textContent='Play';}});
function tick(now){const dt=Math.min(.05,(now-lastTick)/1000||0);lastTick=now;if(viewer&&move){const old=viewer.camera.position.clone(),amount=Number($('speed').value)*dt;if(move==='forward'||move==='back')viewer.camera.translateZ(amount*(move==='forward'?-1:1));if(move==='left'||move==='right')viewer.camera.translateX(amount*(move==='left'?-1:1));if(move==='up'||move==='down')viewer.camera.position.y+=amount*(move==='up'?1:-1);viewer.controls.target.add(viewer.camera.position.clone().sub(old));}if(playing&&manifest&&!loading){const time=(now-playOrigin)/1000;if(time>=manifest.frames.at(-1).time){playing=false;$('play').textContent='Play';if(frameIndex!==manifest.frames.length-1)loadFrame(manifest.frames.length-1).catch(error);}else{const index=nearest(time);if(index!==frameIndex)loadFrame(index).catch(e=>{playing=false;error(e);});}}requestAnimationFrame(tick);}requestAnimationFrame(tick);
try{const fragment=new URLSearchParams(location.hash.slice(1));let saved;if(fragment.has('bridge')&&fragment.has('key')){saved={url:fragment.get('bridge'),key:fragment.get('key')};history.replaceState(null,'',location.pathname);}else saved=JSON.parse(localStorage.getItem(pairKey)||sessionStorage.getItem(pairKey)||'null');if(saved)connect(saved).catch(error);}catch(e){error(e);}
